dist: trusty
language: python
sudo: required

services:
  - docker

cache:
    pip: true
    directories:
        - $HOME/.cache/pip
        - .tox

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

addons:
  postgresql: "9.4"

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py3-cover,coverage
        - python: 3.5
          env: TOXENV=pep8
        - python: 3.6-dev
          env: TOXENV=py36
        - python: nightly
          env: TOXENV=py37
    allow_failures:
        - env: TOXENV=py36
        - env: TOXENV=py37
        - env: TOXENV=py3-cover,coverage

before_install:
  - docker pull raspi/docker-powerdns-travis-ci-rest-test
  - docker run --network host --detach raspi/docker-powerdns-travis-ci-rest-test
  - sudo netstat --listening --protocol inet --numeric

install:
  - travis_retry pip install tox codeclimate-test-reporter codecov

before_script:
  - pip install -U pip
  - psql -c "CREATE ROLE muuri WITH LOGIN PASSWORD 'muuri' VALID UNTIL 'infinity';" -U postgres
  - psql -c "CREATE DATABASE muuri WITH OWNER=muuri ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' CONNECTION LIMIT=-1;" -U postgres
  - cp development.ini-dist development.ini

script:
  - travis_retry tox