"""init

Revision ID: 1
Revises: 
Create Date: 2016-11-15 15:19:22.976794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Unicode(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('added', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("login != ''", name='users_chk_login_not_empty'),
    sa.CheckConstraint("login ~* '^[a-z]{3,}$'", name='users_chk_login'),
    sa.CheckConstraint("password != ''", name='users_chk_pw_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), server_default=sa.text('-1'), nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('userid != -1', name='loginlog_chk_userid_not_default'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loginlog')
    op.drop_table('users')
    ### end Alembic commands ###
