"""init

Revision ID: 1
Revises: 
Create Date: 2016-12-01 13:59:14.057008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnsapis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apitype', sa.Integer(), server_default=sa.text('-1'), nullable=False),
    sa.Column('apikey', sa.Unicode(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('host', sa.Unicode(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('port', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('added', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("host != ''", name='dnsapis_chk_host_not_empty'),
    sa.CheckConstraint('apitype >= 1', name='dnsapis_chk_api_type'),
    sa.CheckConstraint('port <= 65535', name='dnsapis_chk_port_range_high'),
    sa.CheckConstraint('port >= 1', name='dnsapis_chk_port_range_low'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Unicode(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('added', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("login != ''", name='users_chk_login_not_empty'),
    sa.CheckConstraint("login ~* '^[a-z]{3,}$'", name='users_chk_login'),
    sa.CheckConstraint("password != ''", name='users_chk_pw_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), server_default=sa.text('-1'), nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('userid != -1', name='loginlog_chk_userid_not_default'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loginlog')
    op.drop_table('users')
    op.drop_table('dnsapis')
    # ### end Alembic commands ###
